### ISSUE TITLE
Routes and Angular

### ISSUE THREAD

**Issue by analins** [analins/KraftyKitchen#1]
**Main Issue**
I cannot get one of my routes to work...and that's the final piece to having something functional to present. 
I spent the better part of yesterday trying to get it to work, and could not figure it out.

**Minor Issues**
I tried to have my signup form be in a modal, but it doesn't work when it's in the modal...and other smaller things with bootstrap ui 

Issue redirecting from index to profile page...I had this in the last project...I just want to figure out how to do it from my routes...and wondering why redirect('/route') doesn't working.

**Comment by ajhofferber** [comment]
Hey Ana,

Want to try and spike on your route problem?
